version: '3.3'
services:
  minio:
    image: minio/minio
    container_name: minio
    volumes:
      - ./minio/data:/data
    ports:
      - "9000:9000"
    environment:
      - MINIO_ROOT_USER=user
      - MINIO_ROOT_PASSWORD=12345678
    command: server /data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  minio-data: