spring:
  datasource:
    url: jdbc:postgresql://192.168.0.112:5432/forum_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
jwt:
  secret: qBTmv4oXFFR2GwjexDJ4t6fsIUIUhhXqlktXjXdkcyygs8nPVEwMfo29VDRRepYDVV5IkIxBMzr7OEHXEHd37w==
minio:
  access-key: e4PTF1Z5fhhKhCpM46rn
  secret-key: Mal18wYZHCzpMXkT0UGkwvom6JWDMpOr0Ef1ZNzy
  bucket: forum
  url: http://192.168.0.112:9000/