spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/java_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    enabled: true
jwt:
  secret: qBTmv4oXFFR2GwjexDJ4t6fsIUIUhhXqlktXjXdkcyygs8nPVEwMfo29VDRRepYDVV5IkIxBMzr7OEHXEHd37w==
minio:
  access-key: CJgJaRhmKrIA1p5pjaq7
  secret-key: dmBCbe8p1XW5V9iIxKlLGouCEc5u89UtxK91TBgD
  bucket: forum
  url: http://192.168.0.112:9000/